### ISSUE TITLE
¿Dónde debe estar almacenado el certificado?

### ISSUE THREAD

**Issue by fernand0** [gecos-team/autofirma-gecos#1]
Hola,

acabo de actuazliar a Ubuntu 18.04 y Autofirma ya no encuentra el certificado. En versiones anteriores lo conseguí instalar con chromium pero ahora, a pesar de que tengo el  certificado tanto en chromium como en firefox, Autofirma dice que no hay certificado. ¿A qué puede deberse?
Lamento utilizar un 'issue' para esto pero no se muy bien dónde buscar esta información.

**Comment by alfem** [comment]
Nada de lamentos!

El paquete lo hacemos para GECOS, que como está basada en Ubuntu+Mint suele funcionar en la Ubuntu correspondiente. 

La última versión estable de GECOS es la v3, basada en Ubuntu 16.04 (Xenial), y justo ahora estamos empezando a ver las 'sorpresas' que nos depara la Ubuntu 18.04 ('back-to-gnome'). Así que no hemos probado aún autofirma con ésta. 

Así -a bote pronto- puede ser por alguna ruta de las librerías nss instaladas, o por un almacén de certificados que se ha corrompido (pasa a veces). 

Te sugeriría crear un perfil nuevo en Firefox, cargar ahí el certificado y reintentar. Por supuesto contra una aplicación web de firma tirando a moderna, no sea que intente usar un "appletón" de los antiguos :-)

**Comment by alfem** [comment]
¿Puedes probar esta nueva versión?

https://github.com/gecos-team/autofirma-gecos/blob/master/autofirma_1.6.1-gecos9_all.deb

En GECOS usamos Firefox E.S.R. que está un poco por detrás de las versiones 'para el gran público'. Pero las últimas versiones de Firefox usan el formato **sqlite** en lugar de **dbm** para almacenar los certificados (en el fichero cert9.db en vez del antiguo cert8.db).

Así que hemos hecho algún ajuste al script que instala los certificados (Autofirma-Firefox).

Si nos das feedback, sería genial ;-)

**Comment by DocenciaLibre** [comment]
Hola, no soy fernand0 pero estoy en circunstancias similares, ubuntu 18.04 en una instalación nueva. He instalado en el firefox 63 que trae el certificado de la FNMT y autofirma no puede firmar nada porque dice que "el almacén no contiene ningún certificado que se pueda usar para instalar". En ubuntu 16.04 funcionaba todo sin problemas.

**Comment by alfem** [comment]
¿Has usado el paquete de Autofirma del post anterior?

**Comment by DocenciaLibre** [comment]
Sí, el problema sucede con el paquete deb vuestro que enlazas en el post anterior así como en la distribución oficial de autofirma.

**Comment by DocenciaLibre** [comment]
Incluyo el log de autofirma, por si fuese de alguna utilidad. 
Los certificados instalados funcionan correctamente cuando se prueban, por ejemplo, en 
https://www.sede.fnmt.gob.es/certificados/persona-fisica/verificar-estado

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-02T09:15:14.850429Z</date>
  <millis>1541150114850</millis>
  <nanos>429000</nanos>
  <sequence>0</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.ProxyUtil</class>
  <method>setDefaultProxy</method>
  <thread>1</thread>
  <message>Las conexiones para protocolo 'http' son por defecto de tipo: DIRECT</message>
</record>
<record>
  <date>2018-11-02T09:15:14.915709Z</date>
  <millis>1541150114915</millis>
  <nanos>709000</nanos>
  <sequence>1</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.ProxyUtil</class>
  <method>setDefaultProxy</method>
  <thread>1</thread>
  <message>Las conexiones para protocolo 'https' son por defecto de tipo: DIRECT</message>
</record>
<record>
  <date>2018-11-02T09:15:14.917012Z</date>
  <millis>1541150114917</millis>
  <nanos>12000</nanos>
  <sequence>2</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.ProxyUtil</class>
  <method>setProxySettings</method>
  <thread>1</thread>
  <message>No se usara Proxy para las conexiones de red</message>
</record>
<record>
  <date>2018-11-02T09:15:14.919387Z</date>
  <millis>1541150114919</millis>
  <nanos>387000</nanos>
  <sequence>3</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.SimpleAfirma</class>
  <method>main</method>
  <thread>1</thread>
  <message>No se buscaran nuevas versiones de la aplicacion</message>
</record>
<record>
  <date>2018-11-02T09:15:14.931768Z</date>
  <millis>1541150114931</millis>
  <nanos>768000</nanos>
  <sequence>4</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.SimpleAfirma</class>
  <method>printSystemInfo</method>
  <thread>1</thread>
  <message>Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 4.15.0-38-generic
Version de Java: 10.0.2
Arquitectura del JRE: 64
Java Vendor: Oracle Corporation
Localizacion por defecto: en_US
Tamano actual en memoria: 122MB
Tamano maximo de memoria: 1928MB
Memoria actualmente libre: 96MB</message>
</record>
<record>
  <date>2018-11-02T09:15:14.933518Z</date>
  <millis>1541150114933</millis>
  <nanos>518000</nanos>
  <sequence>5</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.SimpleAfirma</class>
  <method>main</method>
  <thread>1</thread>
  <message>Apertura como herramienta de escritorio</message>
</record>
<record>
  <date>2018-11-02T09:15:15.097457Z</date>
  <millis>1541150115097</millis>
  <nanos>457000</nanos>
  <sequence>6</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.SimpleAfirma</class>
  <method>main</method>
  <thread>1</thread>
  <message>Se intenta una precarga temprana de NSS</message>
</record>
<record>
  <date>2018-11-02T09:15:15.130651Z</date>
  <millis>1541150115130</millis>
  <nanos>651000</nanos>
  <sequence>7</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities</class>
  <method>loadNSS</method>
  <thread>1</thread>
  <message>Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/thunderbird/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.mozilla/firefox/b1enjeq5.default' certPrefix='' keyPrefix='' flags='readOnly'"</message>
</record>
<record>
  <date>2018-11-02T09:15:15.142856Z</date>
  <millis>1541150115142</millis>
  <nanos>856000</nanos>
  <sequence>8</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities</class>
  <method>loadNssJava8</method>
  <thread>1</thread>
  <message>NSS necesita una precarga o tratamiento de sus dependencias: java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.&lt;init&gt;(java.io.InputStream)</message>
</record>
<record>
  <date>2018-11-02T09:15:15.146492Z</date>
  <millis>1541150115146</millis>
  <nanos>492000</nanos>
  <sequence>9</sequence>
  <logger>es.gob.afirma</logger>
  <level>SEVERE</level>
  <class>es.gob.afirma.keystores.mozilla.NssKeyStoreManager</class>
  <method>getNssProvider</method>
  <thread>1</thread>
  <message>Error obteniendo el proveedor NSS: java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.&lt;init&gt;(java.io.InputStream)</message>
  <exception>
    <message>java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.&lt;init&gt;(java.io.InputStream)</message>
    <frame>
      <class>java.lang.Class</class>
      <method>getConstructor0</method>
      <line>3302</line>
    </frame>
    <frame>
      <class>java.lang.Class</class>
      <method>getConstructor</method>
      <line>2110</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities</class>
      <method>loadNssJava8</method>
      <line>641</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities</class>
      <method>loadNSS</method>
      <line>684</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.mozilla.NssKeyStoreManager</class>
      <method>getNssProvider</method>
      <line>111</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.mozilla.NssKeyStoreManager</class>
      <method>init</method>
      <line>58</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager</class>
      <method>init</method>
      <line>68</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.AOKeyStoreManagerFactory</class>
      <method>getNssKeyStoreManager</method>
      <line>488</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.AOKeyStoreManagerFactory</class>
      <method>getMozillaUnifiedKeyStoreManager</method>
      <line>519</line>
    </frame>
    <frame>
      <class>es.gob.afirma.keystores.AOKeyStoreManagerFactory</class>
      <method>getAOKeyStoreManager</method>
      <line>116</line>
    </frame>
    <frame>
      <class>es.gob.afirma.standalone.SimpleAfirma</class>
      <method>main</method>
      <line>571</line>
    </frame>
  </exception>
</record>
<record>
  <date>2018-11-02T09:15:15.152326Z</date>
  <millis>1541150115152</millis>
  <nanos>326000</nanos>
  <sequence>10</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.AOKeyStoreManager</class>
  <method>init</method>
  <thread>1</thread>
  <message>Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF</message>
</record>
<record>
  <date>2018-11-02T09:15:15.272360Z</date>
  <millis>1541150115272</millis>
  <nanos>360000</nanos>
  <sequence>11</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.KeyStoreUtilities</class>
  <method>addPreferredKeyStoreManagers</method>
  <thread>1</thread>
  <message>No se ha encontrado un DNIe: java.security.ProviderException: No se ha podido inicializar el proveedor de DNIe: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema</message>
</record>
<record>
  <date>2018-11-02T09:15:15.274235Z</date>
  <millis>1541150115274</millis>
  <nanos>235000</nanos>
  <sequence>12</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.AOKeyStoreManager</class>
  <method>init</method>
  <thread>1</thread>
  <message>Inicializamos el almacen de tipo: G&amp;D SmartCafe con Applet PKCS#15</message>
</record>
<record>
  <date>2018-11-02T09:15:15.282483Z</date>
  <millis>1541150115282</millis>
  <nanos>483000</nanos>
  <sequence>13</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.KeyStoreUtilities</class>
  <method>addPreferredKeyStoreManagers</method>
  <thread>1</thread>
  <message>No se ha encontrado una tarjeta G&amp;D SmartCafe: java.security.ProviderException: No se ha podido inicializar el proveedor: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema</message>
</record>
<record>
  <date>2018-11-02T09:15:15.284050Z</date>
  <millis>1541150115284</millis>
  <nanos>50000</nanos>
  <sequence>14</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities</class>
  <method>getMozillaPKCS11Modules</method>
  <thread>1</thread>
  <message>Se incluiran los modulos nativos de DNIe/CERES si se encuentran configurados</message>
</record>
<record>
  <date>2018-11-02T09:15:15.287446Z</date>
  <millis>1541150115287</millis>
  <nanos>446000</nanos>
  <sequence>15</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities</class>
  <method>getMozillaPKCS11Modules</method>
  <thread>1</thread>
  <message>Obtenidos los modulos externos de Mozilla desde 'pkcs11.txt'</message>
</record>
<record>
  <date>2018-11-02T09:15:15.290217Z</date>
  <millis>1541150115290</millis>
  <nanos>217000</nanos>
  <sequence>16</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager</class>
  <method>init</method>
  <thread>1</thread>
  <message>No se han encontrado modulos PKCS#11 externos instalados en Firefox</message>
</record>
<record>
  <date>2018-11-02T09:15:15.291614Z</date>
  <millis>1541150115291</millis>
  <nanos>614000</nanos>
  <sequence>17</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.SimpleAfirma</class>
  <method>setKeyStoreManager</method>
  <thread>1</thread>
  <message>Establecido KeyStoreManager: Gestor de almacenes de claves Mozilla / Firefox (unificado) con nombre Mozilla / Firefox (unificado)</message>
</record>
<record>
  <date>2018-11-02T09:15:15.454775Z</date>
  <millis>1541150115454</millis>
  <nanos>775000</nanos>
  <sequence>18</sequence>
  <logger>es.gob.afirma</logger>
  <level>INFO</level>
  <class>es.gob.afirma.standalone.SimpleAfirma</class>
  <method>loadDefaultKeyStore</method>
  <thread>1</thread>
  <message>Se omite la carga concurrente de almacen por haberse hecho una precarga previa</message>
</record>
<record>
  <date>2018-11-02T09:15:24.224578Z</date>
  <millis>1541150124224</millis>
  <nanos>578000</nanos>
  <sequence>19</sequence>
  <logger>es.gob.afirma</logger>
  <level>WARNING</level>
  <class>es.gob.afirma.keystores.AggregatedKeyStoreManager</class>
  <method>getAliases</method>
  <thread>30</thread>
  <message>No se pudieron obtener los alias del almacen Mozilla / Firefox (unificado): java.lang.IllegalStateException: Se han pedido alias a un almacen no inicializado</message>
</record>
<record>
  <date>2018-11-02T09:15:24.254318Z</date>
  <millis>1541150124254</millis>
  <nanos>318000</nanos>
  <sequence>20</sequence>
  <logger>es.gob.afirma</logger>
  <level>SEVERE</level>
  <class>es.gob.afirma.standalone.ui.SignPanelSignTask</class>
  <method>doSignature</method>
  <thread>30</thread>
  <message>El almacen no contiene ningun certificado que se pueda usar para firmar: es.gob.afirma.keystores.AOCertificatesNotFoundException: No se han encontrado certificados en el almacen acordes a los filtros establecidos</message>
</record>
</log>

**Comment by alfem** [comment]
Si estaś usando java 10, yo probaría a instalar java 8 hasta que actualicen AutoFirma.

**Comment by DocenciaLibre** [comment]
Tienes razón, haciendo sudo update-alternatives --config java
y eligiendo java-8-openjdk se ha solucionado el problema y ya funciona bien. 
Muchas gracias!!

**Comment by juanconde** [comment]
Si es que desde la plataforma universal que nos prometían en los 90 a la torre de Babel que te encuentras hoy va un abismo. Y menos mal que funciona con OpenJDK! Si hiciese falta la máquina Java de Oracle, habría que añadir al caos de versiones la inminente amenaza de cobro.

**Comment by carlosble** [comment]
Muchas gracias por la info! En mi caso tenia OpenJDK con Java 11 y tampoco funcionaba, la solucion ha sido configurar java para trabajar de nuevo en la version Java 8 como dijo @DocenciaLibre. Muchas gracias :-)

**Comment by fernand0** [comment]
Hola,

puedo confirmar que con el último paquete autofirma_1.6.1-gecos9_all.deb y con java en la versión 8 (lo que se dice arriba "sudo update-alternatives --config java
y eligiendo java-8-openjdk") me funciona (al menos de manera 'independiente', supongo que cuando se llame desde una página web irá tambén).. Hasta ahora no había tenido un momento para probar todo esto. Muchas gracias.

**Comment by jaumeramos** [comment]
Sigo el hilo ya que este post me ha sido de ayuda.
Con la versión 18.04 de Ubuntu, y la versión 1.6.2 de autofirma (desde https://firmaelectronica.gob.es/Home/Descargas.html) utilizando java-8 de Oracle NO funciona, dando el error que comenta @fernand0 en el primer post.
Modificando la  versión de Java con update-alternatives y escogiendo java-8-openjdk la firma me ha funcionado correctamente, tanto desde la aplicación autofirma como desde una página web oficial utilizando Chrome.
Muchas gracias.

**Comment by pjpmosteiro** [comment]
Solucionado con el cambio a openjdk 8.

**Comment by carlosroca2** [comment]
> Tienes razón, haciendo sudo update-alternatives --config java
> y eligiendo java-8-openjdk se ha solucionado el problema y ya funciona bien.
> Muchas gracias!!

He tenido el mismo problema, uso Ubuntu 18.04.2 con Java 10, y no se ha resuelto hasta hacer el cambio a java 8.
Salida de java -version:
"openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)"

Moito obrigado!

**Comment by carlosroca2** [comment]
He tenido el mismo problema, uso Ubuntu 18.04.2 con Java 10, y no se ha resuelto hasta hacer el cambio a java 8.
Salida de java -version:
"openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)"

Moito obrigado!

**Comment by jesusjda** [comment]
Mismo problema pero con Ubuntu 16.04, Tenia Java 12. 
Al hacer que autofirma v1.6.2 se ejecute con Java 8, todo va bien.

Gracias por todo

**Comment by shernandezsantana** [comment]
Mil millones de gracias!!! Deberían poner esto en requisitos para linux, en la página oficial del autofirma. Me he estado comiendo la cabeza por días porque tenía Java Oracle 11!!! :D Ya funciona!

**Comment by acuartango** [comment]
Gracias ! Yo también he tenido problemas con Java 17, acabo de cambiar a Java 8 y funciona. Debería indicarse claramente en la página de descargas de autofirma qué versiones de Java son complatibles.

**Comment by acuartango** [comment]
Gracias ! Yo también he tenido problemas en mi Kubuntu 21.10 con Java 17, acabo de cambiar a Java 8 y funciona. Debería indicarse claramente en la página de descargas de autofirma qué versiones de Java son complatibles con qué sistemas. Al menos un enlace para que los usuarios validemos la compatibilidad ya que entendemos que la casuística es muy grande.

**Comment by alfem** [comment]
El paquete autofirma-gecos tiene las dependencias correctas para que utilice la versión de JAVA que es compatible. 

Si instaláis Autofirma desde otras fuentes, lo suyo sería poner allí los comentarios pertinentes.

**Comment by acuartango** [comment]
Genial,

Ya veo desde dónde descargarlo:
https://github.com/gecos-team/autofirma-gecos

Acaban de sacar la 1.71 de autofirma, ¿Vais a sacar un paquete con esta versión?

gracias por el trabajo !

**Comment by alfem** [comment]
> Acaban de sacar la 1.71 de autofirma, ¿Vais a sacar un paquete con esta versión?

https://github.com/gecos-team/autofirma-gecos/blob/master/autofirma_1.7.1-gecos1_all.deb
