### ISSUE TITLE
Error obteniendo el AOKeyStoreManager - AUTOFIRMA MAC OSX

### ISSUE THREAD

**Issue by shakisha** [gecos-team/autofirma-gecos#2]
In macos mojave, usando tanto Safari que Chrome, en los logs tengo este error:

  <message>Error obteniendo el AOKeyStoreManager: java.lang.NullPointerException</message>

Que puedo hacer para solucionarlo?

**Comment by shakisha** [comment]
Sigo con este mismo error y ninguno contesta

**Comment by alfem** [comment]
Tal y como dice el fichero "Readme", este repositorio contiene el "Paquete para instalar AutoFirma en GECOS/Guadalinex/Ubuntu". 

No está pensado para MacOS ni tenemos forma de probarlo.
